export enum IconEnum {
  Search = 'search',
  Cart = 'cart',
  Instagram = 'instagram',
  Linkedin = 'linkedin',
  Twitter = 'twitter',
  Youtube = 'youtube',
  Facebook = 'facebook',
  Trash = 'trash',
  Minus = 'minus',
  ChevronLeft = 'chevron-left',
  ChevronRight = 'chevron-right',
  Location = 'location',
  ChevronDown = 'chevron-down',
  Add = 'add',
  StarOutline = 'star-outline',
  StarHalf = 'star-half',
  Star = 'star',
  Logout = 'logout',
  EyeCross = 'eye-cross',
  Eye = 'eye',
  Envelope = 'envelope',
  Phone = 'phone',
  HeartEmpty = 'heart-empty',
  Heart = 'heart',
}
